[package]
name = "relibc"
version = "0.1.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[lib]
name = "c"
crate-type = ["staticlib"]

[workspace]
members = ["src/crt0", "cbindgen"]

[build-dependencies]
cc = "1.0.17"

[dependencies]
lazy_static = { version = "*", features = ["nightly", "spin_no_std"] }
rand = { version = "0.5.2", default-features = false }
va_list = { path = "va_list", features = ["no_std"] }

[dependencies.compiler_builtins]
git = "https://github.com/rust-lang-nursery/compiler-builtins.git"
default-features = false
features = ["no-lang-items", "mangled-names"]

[dependencies.ralloc]
path = "ralloc"
default-features = false
optional = true

[target.'cfg(target_os = "linux")'.dependencies]
sc = "0.2"

[target.'cfg(target_os = "redox")'.dependencies]
redox_syscall = { git = "https://gitlab.redox-os.org/redox-os/syscall.git", branch = "relibc" }
spin = "0.4"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
