sys_includes = ["sys/types.h"]
include_guard = "_SYS_TIME_H"
language = "C"

# WORKAROUND:
# Timeval is used by another header, and cbindgen doesn't prefix that with `struct` :|
style = "Both"

[enum]
prefix_with_name = true
