include_guard = "_SYS_IOCTL_H"
language = "C"

# WORKAROUND:
# sgtty is used by another header, and cbindgen doesn't prefix that with `struct` :|
style = "Both"

[enum]
prefix_with_name = true

[export]
include = ["sgttyb", "winsize"]
